"""
TerraRisk Workshop - Configuration
"""

import os
from pathlib import Path

# Base paths
BASE_DIR = Path(__file__).parent.parent
DATA_DIR = BASE_DIR / "data"
MAPS_DIR = DATA_DIR / "maps"
BIVARIATE_DIR = MAPS_DIR / "bivariate"

# Ensure directories exist
MAPS_DIR.mkdir(parents=True, exist_ok=True)
BIVARIATE_DIR.mkdir(parents=True, exist_ok=True)

# Database
DATABASE_PATH = DATA_DIR / "groups.db"

# Workshop settings
INITIAL_CREDITS = 10
MAX_ACTIVE_LAYERS = 2

# Layer configuration
# Cost tiers:
#   1 credit  - Easily accessible data
#   2 credits - Moderate processing
#   3 credits - Complex data
#   4 credits - Most complex (composite indices)
LAYERS_CONFIG = [
    # === GOVERNANÇA (2 créditos cada) ===
    {
        "id": "governance_general",
        "name": "Índice de Governança",
        "category": "governance",
        "description": "Índice UAI geral de capacidade institucional",
        "source": "IBGE - Pesquisa de Informações Básicas Municipais (MUNIC)",
        "formula": "Índice UAI normalizado (0-100) baseado em capacidade institucional municipal",
        "cost": 2,
        "variable": "gobernanza_100",
        "imageFile": "02_Governance_UAI_General.png",
        "colorScale": "positive",
    },
    {
        "id": "governance_climatic",
        "name": "Governança Risco Climático",
        "category": "governance",
        "description": "Índice UAI de capacidade adaptativa frente às mudanças climáticas",
        "source": "IBGE/MUNIC - Sub-índice de políticas climáticas",
        "formula": "Sub-índice UAI filtrado por políticas de mudança climática e adaptação",
        "cost": 2,
        "variable": "UAI_Crisk",
        "imageFile": "01_Governance_UAI_Climatic_Risk.png",
        "colorScale": "positive",
    },
    # === BIODIVERSIDADE ===
    {
        "id": "forest_cover",
        "name": "Cobertura Florestal",
        "category": "biodiversity",
        "description": "Percentual de vegetação natural remanescente",
        "source": "MapBiomas v8 - Coleção Anual de Cobertura e Uso do Solo",
        "formula": "Área de vegetação nativa / Área total do município × 100",
        "cost": 1,
        "variable": "forest_cover",
        "imageFile": "04_Natural_Habitat_Vegetation.png",
        "colorScale": "positive",
    },
    {
        "id": "biodiversity",
        "name": "Riqueza Média de Espécies",
        "category": "biodiversity",
        "description": "Índice médio de riqueza de espécies entre grupos taxonômicos",
        "source": "Map of Life (MOL) + IUCN Red List",
        "formula": "Média de riqueza entre anfíbios, aves, mamíferos e répteis (normalizada 0-1)",
        "cost": 2,
        "variable": "mean_species_richness",
        "imageFile": "03_Biodiversity_Species_Richness.png",
        "colorScale": "positive",
    },
    {
        "id": "pollination",
        "name": "Déficit de Polinização",
        "category": "biodiversity",
        "description": "Déficit de serviços de polinização agrícola",
        "source": "Biota Síntesis",
        "formula": "1 − (oferta de polinização / demanda agrícola), normalizado 0-1",
        "cost": 2,
        "variable": "pollination_deficit",
        "imageFile": "05_Pollination_Deficit.png",
        "colorScale": "negative",
    },
    {
        "id": "composite_biodiversity",
        "name": "Índice Composto de Biodiversidade",
        "category": "biodiversity",
        "description": "Índice composto combinando múltiplas métricas de biodiversidade",
        "source": "Composto multivariado (MapBiomas + MOL + Biota Síntesis)",
        "formula": "Média ponderada: cobertura florestal, riqueza de espécies, déficit de polinização",
        "cost": 4,
        "variable": "idx_biodiv",
        "imageFile": "composite_biodiversity.png",
        "colorScale": "positive",
    },
    # === CLIMA ===
    {
        "id": "flooding",
        "name": "Risco de Inundação",
        "category": "climate",
        "description": "Índice de risco de inundações baseado em exposição e perigo",
        "source": "ANA - Atlas de Vulnerabilidade a Inundações",
        "formula": "Índice de exposição × perigo de inundação (normalizado 0-1)",
        "cost": 1,
        "variable": "flooding_risk",
        "imageFile": "06_Flooding_Risk.png",
        "colorScale": "negative",
    },
    {
        "id": "fire_risk",
        "name": "Índice de Risco de Incêndio",
        "category": "climate",
        "description": "Índice de risco de incêndios florestais baseado em recorrência e intensidade",
        "source": "INPE - Programa Queimadas + FIRMS/NASA",
        "formula": "Índice baseado em frequência, densidade e intensidade de focos de calor (2012-2022)",
        "cost": 3,
        "variable": "fire_risk_index",
        "imageFile": "07_Fire_Risk_Index.png",
        "colorScale": "negative",
    },
    {
        "id": "hydric_stress",
        "name": "Estresse Hídrico",
        "category": "climate",
        "description": "Índice de risco de estresse hídrico por exposição à seca",
        "source": "ANA - Conjuntura dos Recursos Hídricos",
        "formula": "Índice de exposição à seca × vulnerabilidade hídrica (normalizado 0-1)",
        "cost": 3,
        "variable": "hydric_stress_r",
        "imageFile": "08_Hydric_Stress_Risk.png",
        "colorScale": "negative",
    },
    {
        "id": "composite_climate",
        "name": "Índice Composto de Risco Climático",
        "category": "climate",
        "description": "Índice composto combinando riscos de inundação, incêndio e estresse hídrico",
        "source": "Composto multivariado (ANA + INPE)",
        "formula": "Média ponderada: risco de inundação, incêndio e estresse hídrico",
        "cost": 4,
        "variable": "idx_clima",
        "imageFile": "composite_climate.png",
        "colorScale": "negative",
    },
    # === SAÚDE ===
    {
        "id": "dengue",
        "name": "Incidência de Dengue",
        "category": "health",
        "description": "Taxa de incidência de dengue por 100.000 habitantes",
        "source": "DATASUS/SINAN - Sistema de Informação de Agravos de Notificação",
        "formula": "Casos confirmados / População × 100.000 (média 2018-2022)",
        "cost": 3,
        "variable": "dengue",
        "imageFile": "09_Zoonotic_Dengue_Incidence.png",
        "colorScale": "negative",
    },
    {
        "id": "diarrhea",
        "name": "Incidência de Diarreia",
        "category": "health",
        "description": "Taxa de hospitalização por doenças diarreicas",
        "source": "DATASUS/SIH - Sistema de Informações Hospitalares",
        "formula": "Internações por doenças diarreicas / População × 100.000 (média 2018-2022)",
        "cost": 3,
        "variable": "incidence_diarr",
        "imageFile": "10_Water_Pollution_Diarrhea.png",
        "colorScale": "negative",
    },
    {
        "id": "cv_mortality",
        "name": "Mortalidade Cardiovascular",
        "category": "health",
        "description": "Taxa de mortalidade por doenças cardiovasculares",
        "source": "DATASUS/SIM - Sistema de Informações sobre Mortalidade",
        "formula": "Óbitos por doenças cardiovasculares / População × 100.000 (média 2018-2022)",
        "cost": 3,
        "variable": "death_circ_mean",
        "imageFile": "11_Heat_Fire_CV_Mortality.png",
        "colorScale": "negative",
    },
    {
        "id": "resp_hosp",
        "name": "Hospitalização Respiratória",
        "category": "health",
        "description": "Taxa de hospitalização por doenças respiratórias",
        "source": "DATASUS/SIH - Sistema de Informações Hospitalares",
        "formula": "Internações por doenças respiratórias / População × 100.000 (média 2018-2022)",
        "cost": 3,
        "variable": "hosp_resp_mean",
        "imageFile": "12_Heat_Fire_Resp_Hospitalization.png",
        "colorScale": "negative",
    },
    {
        "id": "composite_health",
        "name": "Índice Composto de Saúde",
        "category": "health",
        "description": "Índice composto de carga de doença combinando múltiplos indicadores de saúde",
        "source": "Composto multivariado (DATASUS: SINAN + SIH + SIM)",
        "formula": "Média ponderada: dengue, diarreia, mortalidade CV e hospitalização respiratória",
        "cost": 4,
        "variable": "idx_carga_enfermedad",
        "imageFile": "composite_health.png",
        "colorScale": "negative",
    },
    # === SOCIAL ===
    {
        "id": "population",
        "name": "População",
        "category": "social",
        "description": "População total do município",
        "source": "IBGE - Censo Demográfico 2022",
        "formula": "Contagem direta da população residente",
        "cost": 1,
        "variable": "population",
        "imageFile": "population.png",
        "colorScale": "neutral",
    },
    {
        "id": "rural",
        "name": "Percentual Rural",
        "category": "social",
        "description": "Percentual da população em áreas rurais",
        "source": "IBGE - Censo Demográfico 2022",
        "formula": "População rural / População total × 100",
        "cost": 1,
        "variable": "pct_rural",
        "imageFile": "15_Rural_Population.png",
        "colorScale": "neutral",
    },
    {
        "id": "urban",
        "name": "Percentual Urbano",
        "category": "social",
        "description": "Percentual da população em áreas urbanas",
        "source": "IBGE - Censo Demográfico 2022",
        "formula": "População urbana / População total × 100",
        "cost": 1,
        "variable": "pct_urbana",
        "imageFile": "urban_percentage.png",
        "colorScale": "neutral",
    },
    {
        "id": "poverty",
        "name": "Percentual de Pobreza",
        "category": "social",
        "description": "Percentual da população em situação de pobreza",
        "source": "IBGE - Cadastro Único (CadÚnico) / Censo 2022",
        "formula": "Famílias em situação de pobreza / Total de famílias × 100",
        "cost": 2,
        "variable": "pct_pobreza",
        "imageFile": "13_Poverty_Percentage.png",
        "colorScale": "negative",
    },
    {
        "id": "vulnerability",
        "name": "Índice de Vulnerabilidade",
        "category": "social",
        "description": "Índice composto de vulnerabilidade socioeconômica",
        "source": "Índice composto multivariado (IBGE + CadÚnico)",
        "formula": "Combinação de indicadores socioeconômicos: renda, educação, saúde, habitação",
        "cost": 2,
        "variable": "vulnerabilidad",
        "imageFile": "14_Vulnerability_Index.png",
        "colorScale": "negative",
    },
    # === CORINGA (5 credits each - mystery layers) ===
    {
        "id": "coringa_esgoto",
        "name": "Tratamento de Esgoto",
        "category": "coringa",
        "description": "Percentual da população com tratamento de esgoto adequado",
        "source": "SNIS - Sistema Nacional de Informações sobre Saneamento",
        "formula": "População atendida com tratamento de esgoto / População total × 100",
        "cost": 5,
        "variable": "esgoto_tratado",
        "imageFile": "coringa_esgoto.png",
        "colorScale": "positive",
        "hidden": True,
    },
    {
        "id": "coringa_pmva",
        "name": "PMVA - Município VerdeAzul",
        "category": "coringa",
        "description": "Classificação ambiental dos municípios pelo Programa Município VerdeAzul (IAA)",
        "source": "SMA-SP - Programa Município VerdeAzul 2018",
        "formula": "Índice de Avaliação Ambiental (IAA) - classificação categórica por faixa",
        "cost": 5,
        "variable": "class_iaa",
        "imageFile": "pmva_background.png",
        "colorScale": "categorical",
        "hidden": True,
    },
    {
        "id": "coringa_restauracao",
        "name": "Áreas Prioritárias de Restauração",
        "category": "coringa",
        "description": "Áreas prioritárias de restauração de vegetação nativa",
        "source": "PLANAVEG / SMA-SP - Plano Nacional de Recuperação da Vegetação Nativa",
        "formula": "Classificação de prioridade: Muito alta (4), Alta (3), Média (2), Baixa (1)",
        "cost": 5,
        "variable": "classe_pri",
        "imageFile": "coringa_restauracao.png",
        "colorScale": "negative",
        "hidden": True,
    },
    {
        "id": "coringa_mulheres",
        "name": "População de Mulheres",
        "category": "coringa",
        "description": "População de mulheres por município - Censo 2022",
        "source": "IBGE - Censo Demográfico 2022",
        "formula": "Contagem direta de população feminina por município",
        "cost": 5,
        "variable": "per_mulh_1",
        "imageFile": "coringa_mulheres.png",
        "colorScale": "neutral",
        "hidden": True,
    },
]
